# yaml-language-server: $schema=./config.schema.json

app:
  # ------------------------------------------------------------------
  # Application identity (provided by Primus Labs)
  # ------------------------------------------------------------------
  identity:
    token: "<YOUR_TOKEN>"
    projectId: "<YOUR_PROJECT_ID>"
    programId: "<YOUR_PROGRAM_ID>"

  # ------------------------------------------------------------------
  # Runtime configuration
  # ------------------------------------------------------------------
  runtime:
    version: "0.1.0" # semantic version (x.y.z)
    env: production # development | production
    logVerbose: 0 # 0 (silent) ~ 5 (debug)

  # ------------------------------------------------------------------
  # External services
  # ------------------------------------------------------------------
  services:
    zkvm:
      url: https://api-por.primuslabs.xyz:38080
    data:
      url: http://api-dev.padolabs.org:38101

  # ------------------------------------------------------------------
  # Blockchain configuration
  # ------------------------------------------------------------------
  blockchain:
    network: base-sepolia # base | base-sepolia
    rpcUrl: "https://sepolia.base.org" # optional, override default RPC

    # Required only if subscription type is PLAN_SELF_PAID
    signer:
      privateKey: "<PRIVATE_KEY>"

# --------------------------------------------------------------------
# Exchange API configurations
# At least one exchange must be configured: binance or aster
# --------------------------------------------------------------------
exchanges:
  binance:
    # Binance account #1
    - apiKey: "binance-key-123"
      apiSecret: "binance-secret-abc"
      kind: ["spot", "usds-futures"] # spot | usds-futures | coin-futures | unified

    # Binance account #2 (disabled)
    - apiKey: "binance-key-456"
      apiSecret: "binance-secret-def"
      kind: ["spot", "unified"]
      enabled: false # optional, default: true
      description: "My Binance spot account" # optional, default: ""

  aster:
    - apiKey: "aster-key-123"
      apiSecret: "aster-secret-abc"
      kind: ["spot", "usds-futures"] # spot | usds-futures
