services:
  por-client-demo:
    # build: .
    image: primuslabs/por-client-demo:v0.1.0
    container_name: por-client-demo
    volumes:
      - ./.config.yml:/app/.config.yml:ro
      - ./.state.json:/app/.state.json
    restart: always
